### ISSUE TITLE
Deault / Example

### ISSUE THREAD

**Issue by eguinane** [eguinane/parsnip#3]
Add a default or example configuration object.

Here a Yaml of the current syntax, but it don't and shouldn't take yaml as input, so the exemple need to be a javascript object.

```yaml
usage: sql-gen-field-list.js <table name>

options:
    - user:
        short: U
        data: true
        override: mysql.user
    - host:
        short: H
        data: true
        override: mysql.host
    - database:
        short: D
        data: true
        override: mysql.database
    - update:
        short: u
        help: Write a UPDATE stub.
    - new-old:

arguments:
    - table:
            required: true
            help: The table you want to describe.
```
